name: connection_notifier
description: A Flutter package that notifies when no internet connection as well as providing simple tools that help tracking the internet connection status.
version: 1.0.1
homepage: https://github.com/AmrAbdelmagid/connection_notifier

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  rxdart: ^0.27.7
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
