name: connection_notifier
description: A Flutter package that notifies when there is no internet connection and provides simple tools that help track the internet connection status.
version: 2.0.2
homepage: https://github.com/AmrAbdelmagid/connection_notifier

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  rxdart: ^0.28.0
  flutter:
    sdk: flutter
  internet_connection_checker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
