name: connection_notifier
description: A Flutter package that notifies when no internet connection.
version: 0.0.1
homepage: github.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  internet_connection_checker: ^0.0.1+3
  oktoast: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
