name: connection_notifier
description: A Flutter package that notifies when no internet connection as well as providing simple tools that help tracking the internet connection status.
version: 3.0.0
homepage: https://github.com/AmrAbdelmagid/connection_notifier

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  rxdart: ^0.28.0
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^2.9.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
